name: Python package publish

on:
  workflow_call:
    inputs:
      pdm-username:
        required: true
        type: string
      pdm-password:
        required: true
        type: string
      python-version:
        required: true
        type: string
      os:
        required: false
        type: string
        default: "ubuntu-latest"
      timeout:
        required: false
        type: number
        default: 60


jobs:
  lint:
    timeout-minutes: ${{ inputs.timeout }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ inputs.python-version }}
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('pdm.lock') }}
      - name: Publish package distributions to PyPI
        run: pdm publish --username=${{ inputs.pdm-username }} --password=${{ inputs.pdm-password }}