name: Releasing

on:
  workflow_dispatch:
    inputs:
      release-message:
        description: 'Release message (for example, version of the package)'
        required: true
        type: string

jobs:
  publish:
    name: "Publish (${{ matrix.python-version }}"
    needs: lint
    uses: ./.github/workflows/_publish.yaml
    with:
      python-version: "3.11"
    secrets:
      pdm-username: "${{ secrets.PDM_USERNAME }}"
      pdm-password: "${{ secrets.PDM_PASSWORD }}"
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        name: ${{ inputs.release-message }}
        tag: ${{ inputs.release-message }}